version: '3'

services:
  nodejs:
    build:
      context: .
      dockerfile: Dockerfile
    image: test-react
    restart: unless-stopped
    environment:
      - CHOKIDAR_USEPOLLING=true
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app
      - node_modules:/usr/src/app/node_modules
    stdin_open: true
    tty: true

volumes:
  node_modules:
